name: Bug Report
description: Valid SQL syntax is not supported
labels: [bug]
body:
  - type: dropdown
    attributes:
      label: Dialect
      multiple: true
      options:
        - SQLite
        - MySQL
        - PostgreSQL
    validations:
      required: true
  - type: textarea
    attributes:
      label: Failing SQL
      render: sql
      placeholder: "SELECT * FROM abc;"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
